services:
  app:
    #dockerfile: Dockerfile
    image: 'app:latest'
    ports:
      - "8080:8080"
    build: .
    #container_name: ingsaproj
    depends_on:
      - db
    environment:
      DISPLAY: host.docker.internal:0
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: fattoria
      MYSQL_USER: root
      MYSQL_PASSWORD: Pannocchie98!?
      #DB_URL: jdbc:mysql://127.0.0.1:3307/fattoria
      ##DB_URL: jdbc:mysql://localhost:3306/fattoria
      #DB_USERNAME: root
      #DB_PASSWORD: Pannocchie98!?
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - app-network
      
  db:
    image: mysql:8.1.0
    restart: on-failure
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Pannocchie98!?
      MYSQL_DATABASE: fattoria
      #MYSQL_USER: root
      #MYSQL_PASSWORD: Pannocchie98!?
    ports:
      - "3306:3306"
    volumes:
      - .\mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
