services:
  app:
    #dockerfile: Dockerfile
    image: 'blue563/smart_farm_2_dock_file/your-image:app'
    #ports:
    #  - "8080:8080"
    build: 
      context: .
      dockerfile: Dockerfile.app
    #container_name: ingsaproj
    depends_on:
      - db
    environment:
      DISPLAY: host.docker.internal:0
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: fattoria
      MYSQL_USER: root
      MYSQL_PASSWORD: Pannocchie98!?
      MYSQL_ROOT_PASSWORD: Pannocchie98!?
    command: sh -c "sleep 20s; echo avvio ; java --module-path ./libs/ --add-modules javafx.controls,javafx.fxml -jar /app.jar  "
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - app-network
      
  db:
    image: 'blue563/smart_farm_2_dock_file/your-image:db'
    build: 
      context: .
      dockerfile: Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: $${{ secrets.PASSWORD }}
      #MYSQL_ROOT_PASSWORD: Pannocchie98!?
      MYSQL_DATABASE: fattoria
    ports:
      - "3306:3306"
    volumes:
      - .\\mysql:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
