name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.33
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: fattoria
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install dependencies
      run: ./mvnw install -DskipTests

    - name: Run tests
      env:
        DB_URL: jdbc:mysql://localhost:3306/fattoria
        DB_USERNAME: root
        DB_PASSWORD: root
      run: ./mvnw test

    - name: Build project
      run: ./mvnw package

    # Aggiungi ulteriori passaggi per il deploy se necessario
    # - name: Deploy
    #   run: ./deploy.sh